# Generated by Django 4.2.7 on 2024-01-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_level_chart', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График уровня зарплаты по годам')),
                ('vacancy_number_chart', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График количества вакансий по годам')),
                ('data_table', models.TextField(verbose_name='Таблица данных')),
            ],
            options={
                'db_table': 'custom_demand_table',
            },
        ),
        migrations.CreateModel(
            name='CustomGeography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_salary_chart', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График уровня зарплаты по городам')),
                ('city_vacancy_fraction_chart', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График доли вакансий по городам')),
                ('data_table', models.TextField(verbose_name='Таблица данных')),
            ],
            options={
                'db_table': 'custom_geography_table',
            },
        ),
        migrations.CreateModel(
            name='CustomLastVacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('vacancy_to_parse', models.TextField(max_length=15, verbose_name='Вакансия для парсинга')),
            ],
            options={
                'db_table': 'custom_lastvacancymodel_table',
            },
        ),
        migrations.CreateModel(
            name='CustomMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, verbose_name='Описание профессии')),
                ('job_photo', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Фотография профессии')),
            ],
            options={
                'db_table': 'custom_mainpage_table',
            },
        ),
        migrations.CreateModel(
            name='CustomNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=25, verbose_name='Должность')),
                ('company_logo', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='Логотип компании')),
                ('first_menu_item', models.TextField(max_length=25, verbose_name='Первый пункт меню')),
                ('second_menu_item', models.TextField(max_length=25, verbose_name='Второй пункт меню')),
                ('third_menu_item', models.TextField(max_length=25, verbose_name='Третий пункт меню')),
                ('fourth_menu_item', models.TextField(max_length=25, verbose_name='Четвертый пункт меню')),
                ('fifth_menu_item', models.TextField(max_length=25, verbose_name='Пятый пункт меню')),
                ('creator', models.TextField(max_length=50, verbose_name='Автор')),
            ],
            options={
                'db_table': 'custom_navigation_table',
            },
        ),
        migrations.CreateModel(
            name='CustomSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField(max_length=30, verbose_name='Название таблицы')),
                ('data_table', models.TextField(verbose_name='Таблица данных')),
                ('skills_chart', models.ImageField(upload_to='images_db/%Y/%m/%d', verbose_name='График навыков')),
            ],
            options={
                'db_table': 'custom_skills_table',
            },
        ),
        migrations.DeleteModel(
            name='LastVacancyModel',
        ),
    ]
